package View;

import Controller.*;
import javax.swing.JButton;

/**
 *
 * @author raybnsr
 */
public class MainMenu extends javax.swing.JFrame {
    
    MainMenuController control;

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_keluar = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_tmbh_wisata = new javax.swing.JButton();
        btn_ubh_wisata = new javax.swing.JButton();
        btn_tmbh_pel = new javax.swing.JButton();
        btn_ubh_pel = new javax.swing.JButton();
        btn_tmbh_kend = new javax.swing.JButton();
        btn_ubh_kend = new javax.swing.JButton();
        btn_tmbh_pems = new javax.swing.JButton();
        btn_ubh_pems = new javax.swing.JButton();
        bgmenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_keluar.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        btn_keluar.setText("Exit");
        btn_keluar.setBorder(null);
        btn_keluar.setContentAreaFilled(false);
        jPanel1.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 80, 40));

        btn_exit.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        btn_exit.setText("Logout");
        btn_exit.setBorder(null);
        btn_exit.setContentAreaFilled(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 80, 40));

        btn_tmbh_wisata.setBackground(new java.awt.Color(255, 102, 0));
        btn_tmbh_wisata.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btn_tmbh_wisata.setForeground(new java.awt.Color(255, 255, 255));
        btn_tmbh_wisata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ratings_50px.png"))); // NOI18N
        btn_tmbh_wisata.setText("+ Wisata");
        btn_tmbh_wisata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_tmbh_wisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tmbh_wisataActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tmbh_wisata, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 203, 49));

        btn_ubh_wisata.setBackground(new java.awt.Color(255, 102, 0));
        btn_ubh_wisata.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btn_ubh_wisata.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubh_wisata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Ratings_50px.png"))); // NOI18N
        btn_ubh_wisata.setText("Data Wisata");
        btn_ubh_wisata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_ubh_wisata, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 203, 49));

        btn_tmbh_pel.setBackground(new java.awt.Color(255, 102, 0));
        btn_tmbh_pel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btn_tmbh_pel.setForeground(new java.awt.Color(255, 255, 255));
        btn_tmbh_pel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_People_50px.png"))); // NOI18N
        btn_tmbh_pel.setText("+ Pelanggan");
        btn_tmbh_pel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_tmbh_pel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 203, 49));

        btn_ubh_pel.setBackground(new java.awt.Color(255, 102, 0));
        btn_ubh_pel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btn_ubh_pel.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubh_pel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_People_50px.png"))); // NOI18N
        btn_ubh_pel.setText("Data Pelanggan");
        btn_ubh_pel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_ubh_pel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 203, 49));

        btn_tmbh_kend.setBackground(new java.awt.Color(255, 102, 0));
        btn_tmbh_kend.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btn_tmbh_kend.setForeground(new java.awt.Color(255, 255, 255));
        btn_tmbh_kend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Resume_50px.png"))); // NOI18N
        btn_tmbh_kend.setText("+ Kendaraan");
        btn_tmbh_kend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_tmbh_kend, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 200, 47));

        btn_ubh_kend.setBackground(new java.awt.Color(255, 102, 0));
        btn_ubh_kend.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btn_ubh_kend.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubh_kend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Resume_50px.png"))); // NOI18N
        btn_ubh_kend.setText("Data Kendaraan");
        btn_ubh_kend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_ubh_kend, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 200, 47));

        btn_tmbh_pems.setBackground(new java.awt.Color(255, 102, 0));
        btn_tmbh_pems.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btn_tmbh_pems.setForeground(new java.awt.Color(255, 255, 255));
        btn_tmbh_pems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Cash_in_Hand_50px.png"))); // NOI18N
        btn_tmbh_pems.setText("+ Transaksi");
        btn_tmbh_pems.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_tmbh_pems, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 203, 47));

        btn_ubh_pems.setBackground(new java.awt.Color(255, 102, 0));
        btn_ubh_pems.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        btn_ubh_pems.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubh_pems.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Cash_in_Hand_50px.png"))); // NOI18N
        btn_ubh_pems.setText("Daftar Transaksi");
        btn_ubh_pems.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btn_ubh_pems, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 203, 47));

        bgmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background-menu.png"))); // NOI18N
        jPanel1.add(bgmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 630));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(914, 604));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_tmbh_wisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tmbh_wisataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tmbh_wisataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgmenu;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_tmbh_kend;
    private javax.swing.JButton btn_tmbh_pel;
    private javax.swing.JButton btn_tmbh_pems;
    private javax.swing.JButton btn_tmbh_wisata;
    private javax.swing.JButton btn_ubh_kend;
    private javax.swing.JButton btn_ubh_pel;
    private javax.swing.JButton btn_ubh_pems;
    private javax.swing.JButton btn_ubh_wisata;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void setController(MainMenuController c){
        this.control = c;
        btn_tmbh_wisata.addActionListener(c);
        btn_ubh_wisata.addActionListener(c);
        
        btn_tmbh_kend.addActionListener(c);
        btn_ubh_kend.addActionListener(c);
        
        btn_tmbh_pel.addActionListener(c);
        btn_ubh_pel.addActionListener(c);
        
        btn_tmbh_pems.addActionListener(c);
        btn_ubh_pems.addActionListener(c);
        
        btn_exit.addActionListener(c);
        btn_keluar.addActionListener(c);
    }

    public JButton getBtn_tmbh_kend() {
        return btn_tmbh_kend;
    }

    public JButton getBtn_tmbh_pel() {
        return btn_tmbh_pel;
    }

    public JButton getBtn_tmbh_pems() {
        return btn_tmbh_pems;
    }

    public JButton getBtn_tmbh_wisata() {
        return btn_tmbh_wisata;
    }

    public JButton getBtn_ubh_pems() {
        return btn_ubh_pems;
    }

    public JButton getBtn_ubh_pel() {
        return btn_ubh_pel;
    }

    public JButton getBtn_ubh_wisata() {
        return btn_ubh_wisata;
    }

    public JButton getBtn_ubh_kend() {
        return btn_ubh_kend;
    }

    public JButton getBtn_logout() {
        return btn_exit;
    }

    public JButton getBtn_keluar() {
        return btn_keluar;
    }
    

}
